#!/bin/sh

DISPLAY_CONF=${GMENU2X_DISPLAY_CONF:-/root/gmenu2x/display.conf}

if [ -r "$DISPLAY_CONF" ]; then
    . "$DISPLAY_CONF"
fi

SDL_DISPLAY_W=${SDL_DISPLAY_W:-${GMENU2X_DISPLAY_W:-480}}
SDL_DISPLAY_H=${SDL_DISPLAY_H:-${GMENU2X_DISPLAY_H:-800}}
SDL_DISPLAY_BPP=${SDL_DISPLAY_BPP:-${GMENU2X_DISPLAY_BPP:-32}}
SDL_DISPLAY_X=${SDL_DISPLAY_X:-${GMENU2X_DISPLAY_X:-0}}
SDL_DISPLAY_Y=${SDL_DISPLAY_Y:-${GMENU2X_DISPLAY_Y:-0}}
SDL_DISPLAY_ROTATION=${SDL_DISPLAY_ROTATION:-${GMENU2X_DISPLAY_ROTATION:-}}
SDL_FBDEV=${SDL_FBDEV:-${GMENU2X_FBDEV:-/dev/fb0}}

export SDL_VIDEODRIVER=fbcon
export SDL_FBDEV
export SDL_NOMOUSE=1
export SDL_MOUSEDEV=/dev/null
if [ -n "$SDL_DISPLAY_ROTATION" ]; then
    export SDL_VIDEO_FBCON_ROTATION="$SDL_DISPLAY_ROTATION"
else
    unset SDL_VIDEO_FBCON_ROTATION
fi
export SDL_FB_BROKEN_MODES=1
export SDL_FBCON_VISIBLE_W="$SDL_DISPLAY_W"
export SDL_FBCON_VISIBLE_H="$SDL_DISPLAY_H"
export SDL_FBCON_VISIBLE_X="$SDL_DISPLAY_X"
export SDL_FBCON_VISIBLE_Y="$SDL_DISPLAY_Y"
export SDL_DISPLAY_W
export SDL_DISPLAY_H
export SDL_DISPLAY_X
export SDL_DISPLAY_Y
export SDL_DISPLAY_ROTATION
export SDL_DISPLAY_BPP
