ctrl_interface=DIR=/tmp/manual_miracast_20260920/wpa_ctrl GROUP=netdev
update_config=1
device_name=F1C200S-AIC
device_type=8-0050F204-5
manufacturer=F1C200S
model_name=F1C200S-AIC-WFD
model_number=1
serial_number=1
config_methods=virtual_display virtual_push_button pbc
p2p_go_intent=15
p2p_oper_reg_class=124
p2p_oper_channel=161
p2p_listen_reg_class=81
p2p_listen_channel=6
p2p_no_group_iface=1
driver_param=use_p2p_group_interface=0
